// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8UL4GGVyjXUdnKZKE5YIOIYoeU3eaWKM',
    appId: '1:351285755021:web:dfa1a8fb471089a2e6b6c4',
    messagingSenderId: '351285755021',
    projectId: 'bis-shufersal-coupons',
    authDomain: 'bis-shufersal-coupons.firebaseapp.com',
    storageBucket: 'bis-shufersal-coupons.appspot.com',
    measurementId: 'G-QJVQ91XNM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVHTtXXRXJVm9WLHfGbfYSrLIWhGHv81g',
    appId: '1:351285755021:android:1b1af0a7afaa1e83e6b6c4',
    messagingSenderId: '351285755021',
    projectId: 'bis-shufersal-coupons',
    storageBucket: 'bis-shufersal-coupons.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn9Hu9fZ3Tlevj3_TzsHyexFWaZvZ4HpY',
    appId: '1:351285755021:ios:1ebfe242343ae242e6b6c4',
    messagingSenderId: '351285755021',
    projectId: 'bis-shufersal-coupons',
    storageBucket: 'bis-shufersal-coupons.appspot.com',
    iosClientId: '351285755021-mgf0t1ipvlqd6fhbmigvsvqm0htd4ckd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tenbisShufersalCoupons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn9Hu9fZ3Tlevj3_TzsHyexFWaZvZ4HpY',
    appId: '1:351285755021:ios:1ebfe242343ae242e6b6c4',
    messagingSenderId: '351285755021',
    projectId: 'bis-shufersal-coupons',
    storageBucket: 'bis-shufersal-coupons.appspot.com',
    iosClientId: '351285755021-mgf0t1ipvlqd6fhbmigvsvqm0htd4ckd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tenbisShufersalCoupons',
  );
}
